### ISSUE TITLE
Static Website

### ISSUE THREAD

**Issue by wrightaprilm** [wrightaprilm/treeStartR#1]
Quick Q for you @sckott - I had a previous static (pkgdown) website that was served at my github.io page for the repo. Obviously, that's not there any more. Is it possible to re-enable it in treestartr's new home? Or should I create a separate repo on my own account with the pkgdown-generated docs to serve? 

Thanks!

**Comment by sckott** [comment]
good question. i forgot to make you admin. you should now have access to the Settings tab of the repo. where you can flip that on!

**Comment by wrightaprilm** [comment]
Great, thank you!
